In [1]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

## Task 2

In [32]:
# full weighted graph (with symmetric weights)
n = 10
A = np.random.uniform(low=1, high=11, size=(n, n))

# symmetrization
P = ((A + A.T) / 2)

# normalization - dividing by column sums
P = P / P.sum(axis=0)
P

array([[0.02176591, 0.16267104, 0.14918883, 0.14244371, 0.14970279,
        0.07508425, 0.11561101, 0.11596913, 0.14267763, 0.03810675],
       [0.1368576 , 0.05317762, 0.1043335 , 0.09486515, 0.08455846,
        0.11219015, 0.0341743 , 0.15156472, 0.0619728 , 0.08247277],
       [0.13600252, 0.11305135, 0.14553736, 0.08391641, 0.11365334,
        0.10048128, 0.05057615, 0.09131273, 0.09250654, 0.07287942],
       [0.12763486, 0.10103552, 0.08248259, 0.04927481, 0.10740699,
        0.06634363, 0.14590736, 0.07030673, 0.1237668 , 0.12785188],
       [0.13924686, 0.09348758, 0.11596504, 0.1114967 , 0.05441222,
        0.11775018, 0.09415859, 0.10987989, 0.08849878, 0.10068735],
       [0.07461967, 0.13252583, 0.10954158, 0.07358303, 0.12580866,
        0.11831851, 0.09565336, 0.11933304, 0.15419456, 0.099579  ],
       [0.09804828, 0.03444941, 0.04705177, 0.13809945, 0.08585097,
        0.08162751, 0.15156192, 0.10950114, 0.06863458, 0.13212202],
       [0.1086047 , 0.16871188, 0.0938052

In [29]:
# sums in columns
P.sum(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
# sums in rows
P.sum(axis=1)

array([0.94578224, 1.13642274, 1.04704925, 1.0406696 , 0.9190813 ,
       0.86687175, 0.96632634, 0.96543454, 1.0294203 , 1.08294195])

In [33]:
evals, evecs = np.linalg.eig(P)
idx = np.argmin(np.abs(evals - 1.0)) # index of 1-eigenvalue
v = evecs[:, idx].real
v = v / v.sum()
print(f"Ergodic density: {v}")

Ergodic density: [0.11088867 0.09329231 0.10108759 0.09936038 0.1031437  0.11020256
 0.09404333 0.10384687 0.0996176  0.08451699]


In [58]:
P @ v

array([0.11088867, 0.09329231, 0.10108759, 0.09936038, 0.1031437 ,
       0.11020256, 0.09404333, 0.10384687, 0.0996176 , 0.08451699])

## Task 3

In [48]:
k = 100
P_k = P
for i in range(k):
    P_k = P_k @ P
P_k

array([[0.11088867, 0.11088867, 0.11088867, 0.11088867, 0.11088867,
        0.11088867, 0.11088867, 0.11088867, 0.11088867, 0.11088867],
       [0.09329231, 0.09329231, 0.09329231, 0.09329231, 0.09329231,
        0.09329231, 0.09329231, 0.09329231, 0.09329231, 0.09329231],
       [0.10108759, 0.10108759, 0.10108759, 0.10108759, 0.10108759,
        0.10108759, 0.10108759, 0.10108759, 0.10108759, 0.10108759],
       [0.09936038, 0.09936038, 0.09936038, 0.09936038, 0.09936038,
        0.09936038, 0.09936038, 0.09936038, 0.09936038, 0.09936038],
       [0.1031437 , 0.1031437 , 0.1031437 , 0.1031437 , 0.1031437 ,
        0.1031437 , 0.1031437 , 0.1031437 , 0.1031437 , 0.1031437 ],
       [0.11020256, 0.11020256, 0.11020256, 0.11020256, 0.11020256,
        0.11020256, 0.11020256, 0.11020256, 0.11020256, 0.11020256],
       [0.09404333, 0.09404333, 0.09404333, 0.09404333, 0.09404333,
        0.09404333, 0.09404333, 0.09404333, 0.09404333, 0.09404333],
       [0.10384687, 0.10384687, 0.1038468

In [50]:
# column values should be the same
c0 = P_k[:, 0]
print(np.allclose(P_k - c0[:, None], 0, atol=1e-10)) # all columns are the same
print(f"Ergodic density: {c0}")

True
Ergodic density: [0.11088867 0.09329231 0.10108759 0.09936038 0.1031437  0.11020256
 0.09404333 0.10384687 0.0996176  0.08451699]


In [57]:
np.all(c0 - v < 1e-10) # the same results for both methods

True

In [59]:
P @ c0

array([0.11088867, 0.09329231, 0.10108759, 0.09936038, 0.1031437 ,
       0.11020256, 0.09404333, 0.10384687, 0.0996176 , 0.08451699])

## Task 5

In [ ]:
# implement PageRank and run on a net